const types = {
  FETCH_POSTS: 'FETCH_POSTS',
  VISIBLE_POSTS: 'VISIBLE_POSTS',
  FILTER_POSTS: 'FILTER_POSTS',
  SORT_BY_COMMENTS: 'SORT_BY_COMMENTS',
  SORT_BY_UPVOTES: 'SORT_BY_UPVOTES',
  SORT_BY_DATE: 'SORT_BY_DATE'
};

export default types;